### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by asierzabala**
I translate the extension to spanish. 
The "Change.." button does not fit in one line, I set "#project-directory" style to 460px width but maybe isn't a solution in others languages and I have not commit.

### CODE REVIEW

**Comment by JeffryBooher** [comment]
This looks good. Can you update `package.json` to include `es` in the `i18n` property?

**Comment by blonfu** [comment]
add spanish in package.json

**Comment by JeffryBooher** [comment]
Ooops. Sorry @blonfu for taking so long on this. I'll go ahead and take care of the `package.json` changes. Thanks for the translation!

**Comment by JeffryBooher** [comment]
Sorry for taking so long on merging this. I didn't see that you had updated `package.json`. Thanks for the translation!

**Comment by asierzabala** [comment]
Ok, don't worry. :)

**Pull request merged**
